### ISSUE TITLE
vagrant.sh

### ISSUE THREAD

**Issue by rahul286** [EasyEngine/build-test#1]
vagrant.sh will run on a dedicated server and do following:

- [x] check if virtualbox exists, if not install
- [x] check if vagrant exists, if not install
- [x] check and download boxes for

1. Debian 7 + 8
2. Ubuntu 12.04, 14.04, 16.04
3. Download 32-bit and 64-bit flavors. Total 10 boxes for now.

**Comment by arush-sal** [comment]
Created and Solved in commit  #9cd9e30
